---
---

---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress dev
  publish_command: vuepress build
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
