---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: body
  label: Body
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
- type: text
  name: description
  label: Description
  description: Used for SEO optimization
  config:
    required: true
